### ISSUE TITLE
package updates needed

### ISSUE THREAD

**Issue by dbj** [dillonkearns/elm-pages-starter#20]
There are a few packages in package.json and elm.json that need updating:

### In package.json

* "elm-pages": "1.4.3" // was "1.4.0"
* "highlight.js": "???" // is "9.15.10" but this is very old - should it be upgraded to "9.18.x" or "10.2.x"?
* "elm-format": "elm0.19.1" // was "0.8.2"; this will install "0.8.3"

### In elm.json

* "dillonkearns/elm-markdown": "5.0.0" // is "4.0.2"
* "dillonkearns/elm-pages": "6.0.0" // is "5.0.1"
* "justinmimbs/date": "3.2.1" // is "3.2.0"
* "mdgriffith/elm-ui": "1.1.8" // is "1.1.6"

**Comment by dillonkearns** [comment]
Should be all good now 👍 

I'll get dependabot set up so I can merge in the non-breaking upgrades automatically.
